### ISSUE TITLE
Autor Feld fehlt

### ISSUE THREAD

**Issue by JBlond** [YourMJK/dreimetadaten#11]
Beim Parsen der Daten fiel mir auf, dass bei den Folgen 29 und 175 das Feld `autor` im json fehlt.

**Comment by YourMJK** [comment]
Danke für das Issue.  
Das ist tatsächlich Absicht!

Folge 29 ist kein richtiger Fall, sondern lediglich eine Sammlung von Melodien aus den vorherigen Hörspielen als reine Musik-CD.  
Dementsprechend gibt es hier keinen "Autor" im eigentlichen Sinne, höchstens Komponisten.

Der Jubiläumsfall 175 besteht aus drei Teilen, die jeweils von verschiedenen Autor:innen geschrieben wurden.  
Deshalb findest du hier kein `autor` Feld im übergeordneten Objekt, dafür aber in den Objekten des `teile` Arrays.

Hoffe das hilft dir weiter, viel Spaß beim Parsen!  
(würde mich übrigens interessieren, für welches Projekt du die Daten verwendest)

**Comment by JBlond** [comment]
Ich habe erstmal eine Liste gemacht, um mein eigenes Rating zu machen 
https://gist.github.com/JBlond/82e5821ad285a0c6d1ca75eeab53e276
