### ISSUE TITLE
Alle Cover Bilder von Kosmos sind weg

### ISSUE THREAD

**Issue by evilpie** [YourMJK/dreimetadaten#13]
Scheinbar gibt es die Bilder nicht mehr auf AWS. Archive.org hat aber scheinbar eine Kopie von vielen (allen?): https://web.archive.org/web/20230601192947/http://dreimetadaten.de/

z.B: https://web.archive.org/web/20220708021919/https://s3.eu-central-1.amazonaws.com/kosmos.de/media/image/f4/06/7d/0888751320123593a75c5abfa5.jpg

**Comment by YourMJK** [comment]
Vielen Dank für die Info!

Das ist schade, aber sollte kein allzu großes Problem sein.
Ich dürfte von (fast) allen noch ein lokales Backup haben und vielleicht sind sie nur zu einem neuen Bucket umgezogen und man findet sie jetzt woanders online.
Ansonsten werde ich auf archive.org zurückgreifen müssen.

Ich schaue mir das die Tage mal an.

**Comment by YourMJK** [comment]
Kleines Update:
* Es scheint, als sei kosmos.de für das Hosten ihrer Bilder von AWS auf eine deutsche Cloud-Alternative umgestiegen: netformic.com
Ich denke mal, die Artikel, die nicht mehr im Sortiment waren (u.A. die Hörspiel-CDs), sind nicht mitumgezogen.
* Mein lokales Backup der Bilder beinhaltet nicht die Original-JPG-Dateien, sondern "nur" deren Pixelinformationen. Daraus könnte man natürlich verlustfrei PNGs erzeugen.
* **Die Bilder sind zum Glück alle auf archive.org**

Das macht es mir natürlich leicht und ich muss nur die URLs mit den archive.org-Versionen ersetzen.

Falls es wer braucht, hier ist die Tabelle mit den URLs für die ursprünglichen kosmos.de-Produktseiten und deren AWS-Bilder (mit ein paar wenigen Lücken):
[kosmos-de-d3f.tsv](https://github.com/YourMJK/dreimetadaten/files/13664491/kosmos-de-d3f.csv)

(hab' ich dann doch länger als ein paar Tage vor mir hingeschoben, ups)

**Comment by YourMJK** [comment]
Es gibt neue interessante Informationen zu dem Thema, ich hab' Antwort vom Kosmos-Support bekommen:

> Nach Rücksprache mit der Fachabteilung, sollten die Hörspiele voraussichtlich in der zweiten Jahreshälfte 2024 wieder online sein.
