### ISSUE TITLE
Schreibfehler Folge 170

### ISSUE THREAD

**Issue by CMD-Golem** [YourMJK/dreimetadaten#17]
Bei der Folge 170 ist in der Beschreibung ein Fehler drin. Und zwar heisst es im zweiten Satz nicht: 'Der der verbietet', sondern, 'Doch der verbietet'

**Comment by YourMJK** [comment]
Vielen Dank für den Hinweis!

Du hast Recht, die [offizielle dreifragezeichen.de-Seite](https://dreifragezeichen.de/produktwelt/details/strasse-des-grauens) (welche für diese Folge die Quelle für die Beschreibung war) hat den gleichen Fehler, aber auf der CD steht es richtig.

Werde ich gleich korrigieren, danke!
