### ISSUE TITLE
Autorenbilder

### ISSUE THREAD

**Issue by JBlond** [YourMJK/dreimetadaten#20]
Es wäre cool auch Bilder von den Autoren zu haben. Spontan habe ich folge gefunden

Henrik Buchner http://www.hendrikbuchna.de/reqs/img/gallery/galerie_01_hendrik/1_Autorenfoto.jpg
André Minninger https://cdn.smehost.net/hcmssmeappscom-delabelsprod/news/2022/andre-minninger-happy-birthday.png

**Comment by YourMJK** [comment]
Das ist eine nette Idee, aber ich glaube für dieses Projekt ist mir das etwas zu subjektiv.  

Was aber andererseits etwas objektiver und vielleicht auch ganz praktisch wäre, sind **Links zu den Wikipedia-Seiten** der Autoren (oder, wenn nicht vorhanden, zu ihren Homepages).  
Dort sind ja dann auch meistens Bilder vorhanden.

Da ich mit Version 2.0 ohnehin unter anderem eine Personendatenbank hinzugefüge, könnte man das sogar auch mit den *Sprechern* weiterführen.  
Wäre bei ~1000 Personen zwar sehr viel Arbeit, ginge aber auch stückweise und vielleicht erstmal mit den bekanntesten.

Was meinst du?  

Was wäre denn dein konkreter Anwendungsfall für die Autorenbilder gewesen? Für Plex?  
Oder einfach nur der Vollständigkeit halber?

**Comment by JBlond** [comment]
Ich nutze die Bilder in Audiobookshelf. 

![grafik](https://github.com/YourMJK/dreimetadaten/assets/2391810/6122d750-9a3c-46c5-a0cc-76c3bb027658)

**Comment by JBlond** [comment]
### Episoden pro Autor

| Anzahl | Name |
|--------|------|
| 44 | André Marx |
| 43 | Marco Sonnleitner |
| 28 | Ben Nevis |
| 24 | Hendrik Buchna |
| 23 | Kari Erlhoff |
| 19 | André Minninger |
| 16 | Brigitte-Johanna Henkel-Waidhofer |
| 15 | M. V. Carey |
| 15 | Christoph Dittert |
| 15 | William Arden |
| 11 | Robert Arthur |
| 9 | Astrid Vollenbruch |
| 4 | Marc Brandel |
| 4 | G. H. Stone |
| 4 | Megan & H. William Stine |
| 3 | Tim Wenderoth |
| 2 | Katharina Fischer |
| 2 | Peter Lerangis |
| 2 | Nick West |
| 1 | William McCay |
| 1 | Katrin Wiegand |
| 1 | Megan Stine |
| 1 | Ivar Leon Menger |
| 1 | Markus Winter |
| 1 | Ivar Leon Menger, John Beckmann |
| 1 | Rose Estes |
| 1 | Christoph Dittert, Kari Erlhoff |

**Comment by YourMJK** [comment]
Ich überleg' mir was, vielleicht baue ich es doch ein!
