### ISSUE TITLE
Fehler in Beschreibung bei Folge 45

### ISSUE THREAD

**Issue by CMD-Golem** [YourMJK/dreimetadaten#22]
Ich habe bei der Folge 45 nochmals einen Fehler in der Beschreibung gefunden. Und zwar heisst es im dritten Satz nicht: 'zunächst Besonderes', sondern, 'zunächst nichts Besonderes'. Scheint auch wieder der Fehler von dreifragezeichen.de zu sein.

**Comment by YourMJK** [comment]
Vielen Dank, werd' ich korrigieren!
