### ISSUE TITLE
Korrektur von Fehlern in Beschreibungen

### ISSUE THREAD

**Issue by odincat** [YourMJK/dreimetadaten#24]
Erst einmal vielen Dank für die Erstellung und Pflege dieses Datensatzes.
Der hat mir bei meinem neuen Projekt, das demnächst veröffentlicht werden soll ;), wirklich *extrem* geholfen.

Für das Projekt habe ich Großteile der Daten in eine relationale Datenbank übertragen, inklusive Zuordnung von Rollen und Sprechern.
Dabei sind mir einige Tippfehler (hauptsächlich in Beschreibungen) aufgefallen, die ich korrigiert habe und nun auch dem originalen Datensatz zugutekommen lassen möchte.

Übrigens: Die Fehler, die ich vor einiger Zeit bei den Sprechern und Protagonisten fand, sind schon alle behoben. :+1: 
Daher hier nur die folgenden, abgeglichen vom v2 Branch:

|Folge| Ort | | Quelle |
|---|---|---|---|
|und der Doppelgänger|Rolle| Jan Carew -> Ian Carew|[Quelle](https://diedreifragezeichen.fandom.com/wiki/Der_Doppelg%C3%A4nger)|
|und die schweigende Grotte|Beschreibung|Sie -> Sind|[Quelle](https://www.amazon.de/-/en/Die-Drei/dp/B08VTWDX88)|
|Feuermond|Beschreibung|verschollenes -> verschollenen|[Quelle](https://www.amazon.de/-/en/Die-drei/dp/B001ET21L2)|
|/|Autorin|Brigitte-Johanna Henkel-Waidhofer -> Brigitte Johanna Henkel-Waidhofer (ohne Bindestricht im Vornamen)|[Quelle](https://de.wikipedia.org/wiki/Brigitte_Johanna_Henkel-Waidhofer)|
|Schrecken aus dem Moor|Beschreibung|jahrtausende -> Jahrtausende|[Quelle](https://www.amazon.de/-/en/Die-Drei/dp/B001GHD3U0)|
|Der geheime Schlüssel|Beschreibung|~dem Ersten Detektiv -> dem **e**rsten Detektiv~|[Quelle](https://i.weltbild.de/p/die-drei-fragezeichen-hoerbuch-119-der-geheime-345768229.jpg); Mein Fehler, ist im Original tatsächlich auch groß geschrieben|
|Gekaufte Spiele|Beschreibung|Duggan -> Trainer Duggan|[Quelle](https://www.amazon.de/-/en/Die-drei/dp/B00005Q4Z5)|
|und der magische Kreis|Beschreibung|der der -> der|
|Tatort Zirkus|Beschreibung|[...] unschuldig wie sie behauptet -> unschuldig, wie sie behauptet|[Quelle](https://www.amazon.de/Die-drei-Fragezeichen-Tatort-Zirkus/dp/B00005Q4Z9)|
|Der Geist des Goldgräbers|Beschreibung|[...] irgendeiner John Dewey! -> irgendeiner. John Dewey|[Quelle](https://www.3fragezeichen.de/?ziel=https://www.3fragezeichen.de/buchdb.php?buch=177)|
|Der Biss der Bestie|Beschreibung|Zugegeben das [...] -> Zugegeben, das [...]|
|und die Geisterinsel|Beschreibung|diese Wissen -> dieses Wissen|
|und die singende Schlange|Beschreibung|zu recht -> zu Recht|
|und das Azthekenschwert|Beschreibung|Spürsinnsinn -> Spürsinn|
|und der rote Rächer|Beschreibung|Jutsus -> Justus|
|Gefährliches Quiz|Beschreibung|Anführungszeichen um "Wer knackt die Nuss?" fehlen.|[Quelle](https://media1.jpc.de/image/w1155/rear/0/0743219432827.jpg)|
|und der sprechende Totenkopf|Beschreibung|enthält: -> enthält;|https://www.amazon.de/Die-drei-Fragezeichen-sprechende-Totenkopf/dp/B00005Q4X5|
|und der Phantomsee|Beschreibung|gelunge -> gelungen|
|und der Phantomsee|Beschreibung|mächten -> möchten |
|Brainwash: Gefangene Gedanken|Beschreibung|Eine Geschichten -> Eine Geschichte|[Quelle](https://i.weltbild.de/p/die-drei-brainwash-gefangene-gedanken-345773269.jpg)|
|und das Hexenhandy|Beschreibung|Küstenstädchen -> Küstenstädtchen|
|und das Volk der Winde|Beschreibung|tanzenden Sauerier -> "Tanzenden Saurier"|[Quelle](https://www.amazon.de/Die-drei-Fragezeichen-Folge-Winde/dp/B00005Q4YD)|
|Fußball-Teufel|Beschreibung|Hookes Nose -> Hooked Nose|[Quelle](https://www.amazon.de/164-Fu%C3%9Fball-Teufel-Die-Drei/dp/B00D4FCCS6)
|und der Teufelsberg|Beschreibung|die junge -> die Jungen|[Quelle](https://media1.jpc.de/image/w1155/rear/0/0743213881928.jpg)|
|und der Teufelsberg|Beschreibung|dunkeln -> Dunkeln|[Quelle](https://media1.jpc.de/image/w1155/rear/0/0743213881928.jpg)|
|und der Teufelsberg|Beschreibung|dransein -> dran sein|[Quelle](https://media1.jpc.de/image/w1155/rear/0/0743213881928.jpg)|

**Comment by YourMJK** [comment]
Wow, das ist wirklich sehr wertvoll, vielen Dank!
Ich hoffe, den Datensatz irgendwann so fehlerfrei wie möglich zu bekommen und das ist ein weiterer Schritt in diese Richtung, denke ich.
Ich schaue mir das die Tage genauer an übernehme die Korrekturen :)

Die offizielle dreifragezeichen.de als Quelle (Beschreibungen) scheint ja wirklich sehr unzuverlässig zu sein …
Darf ich fragen, was du als Quelle für die Korrekturen aus der Tabelle ohne Quellenangaben verwendet hast?
Die CD-Inlays? Oder hast du auch manuell nach "eigener Meinung" korrigiert?
Über sowas wie Anführungszeichen und Groß-/Kleinschreibung bei Eigennamen lässt sich ja z.B. streiten …

> Für das Projekt habe ich Großteile der Daten in eine relationale Datenbank übertragen, inklusive Zuordnung von Rollen und Sprechern.

Oh man, was für ein Timing …
Da haben wir wohl zufällig gleichzeitig an dem Gleichen gearbeitet :D

Wie du ja vielleicht gesehen hast, bin ich derzeit intensiv mit v2.0 beschäftigt.
Diese Woche habe ich u.a. den gesamten Datensatz auch in ein relationales Modell migriert (siehe mein PR #23 von gestern) und wollte mich über's Wochenende für ein Datenbank-System/Integration entscheiden und dann zukünftig zusätzlich zu JSON ein SQL-Dump als SSOT im Repository hinterlegen.
Hier kannst du schonmal meine WIP-Tabellen als TSVs sehen (lediglich die Autorenzuordnung bei Hörspielen mit mehreren Teilen ist noch nicht einwandfrei):
[tsv.zip](https://github.com/YourMJK/dreimetadaten/files/14964558/tsv.zip)

Und letztens habe ich ja eben die ganzen Sprecherdaten korrigiert und alle Namen kanonisiert (PR #18), u.a. in Vorbereitung für das relationale Modell.
Das war ein Riesenaufwand (im Grunde alle ~1000 Namen manuell gecheckt, hoerspielforscher.de war aber eine große Hilfe), dafür bin ich hier jetzt sehr zuversichtlich, was die Korrektheit betrifft.

> Der hat mir bei meinem neuen Projekt, das demnächst veröffentlicht werden soll ;), wirklich extrem geholfen.

Das freut mich sehr zu hören! Bitte unbedingt Bescheid geben, wenn du es veröffentlichst, interessiert mich sehr …
(info@dreimetadaten.de)

BTW: Die Version ist zwar noch nicht richtig veröffentlicht, aber vielleicht hast du ja schon gesehen, dass mit v2.0 der Datensatz unter CC BY 4.0 zur Verfügung steht.
Wenn irgendwo in deinem Projekt dreimetadaten.de und/oder dieses Repository als Quelle angegeben wird, wär das cool :)

**Comment by odincat** [comment]
Sehr gerne!

> Die offizielle dreifragezeichen.de als Quelle (Beschreibungen) scheint ja wirklich sehr unzuverlässig zu sein …

Das war auch meine Erfahrung, letztendlich habe ich wirklich viel mit den CD-Inlays (oder zumindest mit den Fotos davon) gearbeitet, gerade was Satz-, Anführungszeichen und Namen anging.

> Darf ich fragen, was du als Quelle für die Korrekturen aus der Tabelle ohne Quellenangaben verwendet hast?

Ich habe mir alle Beschreibungen vom Server als HTML-Datei mit Textfeldern ausgeben lassen, sie anschließend mit der [LanguageTool-Erweiterung](https://languagetool.org/) überprüft und dann eben manuell geschaut, was Sinn ergibt. Bei so Sachen wie "gelunge", "Küstenstädchen" oder "Spürsinnsinn" habe ich es irgendwie nicht als nötig erachtet, nochmal nachzusehen.

Für Fälle wie "Hookes Nose" (beim Fußballteufel) habe ich dann einfach auf die Fotos der CD-Inlays geschaut. Wie wir ja schon festgestellt haben, ist die offizielle Seite ja nicht gerade fehlerfrei...

Ich werde gleich nochmal ein paar Quellen ergänzen. Manches ist auch nicht gerade fatal, guck einfach was du übernehmen möchtest. 

Für meinen Datensatz habe ich z.B. auch die alte Rechtschreibung "korrigiert". Das ist hier aber wahrscheinlich nicht das Ziel, da die Daten ja möglichst nah am Original sein sollen.

> Hier kannst du schonmal meine WIP-Tabellen als TSVs sehen [...]

Danke dir, werde ich mir mal ansehen.

> Oh man, was für ein Timing …

In der Tat lustig, ich kann dir sonst auch noch gerne meine Tabellen zukommen lassen. Bei mir habe ich halt u.a. mehrere Teile in eine einzelne Folge zusammengefasst; zugegebenermaßen aus Faulheit.

> Und letztens habe ich ja eben die ganzen Sprecherdaten korrigiert und alle Namen kanonisiert (PR https://github.com/YourMJK/dreimetadaten/pull/18), u.a. in Vorbereitung für das relationale Modell. [...]

Das kann ich mir gut vorstellen, dass das gedauert hat. Werde meine Datenbank dann dahingehend wohl nochmal damit abgleichen. Ganz so gründlich habe ich das nämlich nicht gemacht.

>  Bitte unbedingt Bescheid geben, wenn du es veröffentlichst, interessiert mich sehr …

Mach ich :)

Credits verstehen sich ja von selbst. Ich würde den Hinweis auch im Repo geben, folgendes steht aber schon im Footer:
```html
<span>Datensatz basierend auf <a class="underline" href="https://github.com/YourMJK/dreimetadaten" target="_blank">dreimetadaten</a>.</span>

```
Ist das so okay? Sag gerne Bescheid, falls du dahingehend noch Vorschläge hast.

Dann viel Erfolg bei der Auswahl einer Datenbank. Ich nutze PostgreSQL, aber im Prinzip kann man ja so ziemlich alles verwenden, was vernünftige Relations beherrscht.

**Comment by YourMJK** [comment]
> Bei so Sachen wie "gelunge", "Küstenstädchen" oder "Spürsinnsinn" habe ich es irgendwie nicht als nötig erachtet, nochmal nachzusehen.

Ja logisch!

> Ich werde gleich nochmal ein paar Quellen ergänzen. Manches ist auch nicht gerade fatal, guck einfach was du übernehmen möchtest.

Danke! Sieht eh gut aus, werd ich wahrscheinlich 1:1 übernehmen.

> Für Fälle wie "Hookes Nose" (beim Fußballteufel) habe ich dann einfach auf die Fotos der CD-Inlays geschaut. Wie wir ja schon festgestellt haben, ist die offizielle Seite ja nicht gerade fehlerfrei...

Ich glaube, da sitzt irgendein Praktikant, der die Texte nochmal manuell abtippt. Anders kann ich mir die ganzen Fehler (auch bei den Sprecher:innen) nicht erklären.
Wenn ich eine neue Folgen einpflege, gleiche ich deswegen auch immer alles nochmal Buchstabe für Buchstabe mit dem CD-Inlay ab.

> Für meinen Datensatz habe ich z.B. auch die alte Rechtschreibung "korrigiert". Das ist hier aber wahrscheinlich nicht das Ziel, da die Daten ja möglichst nah am Original sein sollen.

Genau, ich glaube, alte Rechtschreibung hab ich bisher immer gelassen.

> Ist das so okay?

Klar, das ist perfekt, vielen Dank! :)

**Comment by YourMJK** [comment]
Bei "Der Geist des Goldgräbers" habe ich statt deiner Quelle (welche eher für das Buch zu seien scheint) [diese](https://i.weltbild.de/p/die-drei-der-geist-des-goldgraebers-folge-177-345775213.jpg) für das CD-Inlay verwendet (gleicht sich auch mit anderen Bildern ab, die man im Internet findet) und eine andere Formulierung, plus noch viel mehr Abweichungen entdeckt und korrigiert:
* Dead Mans Canyon -> Dead Man's Canyon
* **irgendeiner. John Dewey kam -> irgendeiner, sondern John Dewey! Der aber kam**
* seinem Gold zu nahe kommt -> seinem Gold jemals zu nahe kommen würde
* steht fest: Alles Legende! -> steht fest: alles Legende!

Lustigerweise ist auf dem originalen CD-Inlay dafür noch ein eigener Fehler: "Doch als in **der der** darauffolgenden Nacht". Den hab ich mal nicht verschlimmbessert ;)

---

Ähnliches bei "Der geheime Schlüssel", da habe ich statt deiner zurückgenommen Korrektur dafür etwas anderes gefunden:
* der geniale Spielzeugmacher spurlos verschwindet -> der geniale Spielzeugmacher **Felix Kopperschmidt** spurlos verschwindet

---

… bei "Tatort Zirkus":
* steht fest: das war kein Unfall! -> steht fest: Das war kein Unfall!
* Die drei Junior-Detektive sind bereit -> Die Drei ??? sind bereit -> Die drei ??? sind bereit
(das "drei" ist sonst immer klein, so habe ich es rückwirkend damals auch für ältere Fälle "korrigiert")

---

… und bei "Der Biss der Bestie" weichen die Beschreibungen extrem stark von einander ab:

> Zugegeben, das Säbelzahntigerskelett mit den riesigen Fangzähnen im Naturkundemuseum von Rocky Beach sieht sehr bedrohlich aus. Aber dass es nachts durch die Gegend spukt, kann Justus nun wirklich nicht glauben! Wer oder was treibt dann sein Unwesen im \"Geistermuseum\", wie der Ort von den Nachbarn schon genannt wird? Die drei ??? gehen den Spuren nach. Und entdecken das Unfassbare …

vs.

> Kann eine tote Bestie beißen? Das Skelett des Säbelzahntigers im Naturkundemuseum von Rocky Beach sieht zwar sehr bedrohlich aus, doch dass es den Leiter Dr. Wadleigh attackiert haben soll, kommt den drei ??? äußerst merkwürdig vor. Aber wer oder was treibt dann nachts sein Unwesen im Museum?
Justus, Peter und Bob gehen den Spuren nach. Und entdecken das Unfassbare …

------

Ich habe die anderen jetzt nicht weiter gecheckt, aber ich denke, es ist offensichtlich, dass – abgesehen von den offensichtlichen Fehlern – die Beschreibungstexte allgemein noch viele Abweichungen zu den Beschreibungen auf den CD-Inlays aufweisen.
Das liegt wohl größtenteils daran, dass dreifragezeichen.de oftmals die Buchbeschreibungen statt den Hörspielbeschreibungen reinkopiert (oder eher abgetippt?) hat.

Ich werde die Rollen- und Autorin-Korrekturen jetzt erstmal direkt übernehmen und deine Korrekturen für die Beschreibungen in einen zukünftigen PR für v2.0 schieben, bei dem ich generell nochmal manuell ALLE Texte mit den CDs abgleichen und entsprechend korrigieren werde …

Auf jeden Fall trotzdem nochmal vielen Dank!
Vor allem auch jetzt durch das indirekte Aufmerksammachen auf das Chaos bei den Beschreibungen.

**Comment by odincat** [comment]
Oha, das scheint dann wohl doch ein größeres Ausmaß zu haben als vermutet.

> Das liegt wohl größtenteils daran, dass dreifragezeichen.de oftmals die Buchbeschreibungen statt den Hörspielbeschreibungen reinkopiert (oder eher abgetippt?) hat.

Ich vermute es halt mittlerweile ehrlich, dass die jemand stundenlang (!) abtippen durfte und auch immer noch darf. Am besten noch von den echten Büchern. 😆

Vielleicht ~hatten~ haben sie keine vernünftige Datenbank oder verwenden sie nicht. Sogar bei ["Yacht des Verrats"](https://www.dreifragezeichen.de/produktwelt/details/die-yacht-des-verrats-1), die Folge ist ja recht aktuell, sind **zwei** Leerzeichen zu viel an einer Stelle in der Beschreibung. (Klar, ist nicht wirklich schlimm, aber trotzdem irgendwie lustig).

> … und bei "Der Biss der Bestie" weichen die Beschreibungen extrem stark von einander ab:

Jetzt wo du es schreibst, erinnere ich mich tatsächlich auch vage an solche Diskrepanzen. War zwar sehr verwundert, habe diese dann aber offensichtlich nicht mehr weiter verfolgt.

> Ich werde die Rollen- und Autorin-Korrekturen jetzt erstmal direkt übernehmen und deine Korrekturen für die Beschreibungen in einen zukünftigen PR für v2.0 schieben, bei dem ich generell nochmal manuell ALLE Texte mit den CDs abgleichen und entsprechend korrigieren werde …

Jo, das ist wahrscheinlich der einzige Weg, um auf der sicheren Seite zu sein. Ist natürlich eine Heidenarbeit, wobei die Anzahl der Folgen ja gerade noch so "klein" ist, dass es sich manuell bewältigen lässt.

> Auf jeden Fall trotzdem nochmal vielen Dank!

Gerne, das kann ich aber auch genau so zurückgeben, die Arbeit und Mühe, die du hier hineinsteckst, ist wirklich phänomenal. Gerade wenn man bedenkt, dass die offiziellen Quellen nicht zuverlässig verwertbar sind. Und das haben wir ja nun doch an "der einen oder anderen Stelle" feststellen dürfen...

**Comment by YourMJK** [comment]
> Oha, das scheint dann wohl doch ein größeres Ausmaß zu haben als vermutet.

Oh ja … hat dann doch länger gedauert, als gedacht!

Überraschenderweise auf [weltbild.de](https://www.weltbild.de/hoerbuecher-hoerspiele/hoerspiele-kinder/die-drei-fragezeichen?seite=1&sort=5) konnte ich dann endlich zuverlässig recht gute (~1000px) Scans bzw. digitale Bilder der rückseitigen CD-Inlays von allen Folgen finden – und eben auch von den neusten Versionen, d.h. im Falle der älteren (<121) Folgen die Re-Releases von 2005 ohne "EUROPA Logo!"- und Alfred Hitchcock-Logo.
[Discogs](https://www.discogs.com/de/label/294091-Die-Drei?page=1) und Ebay waren auch eine große Hilfe.

Die habe ich dann genutzt, um in Fleißarbeit für jede einzelne Folge die Beschreibungen u.a. mit Hilfe von macOS's eingebautem OCR (beeindruckend genau) zu übertragen, zu korrigieren, jede Änderung sorgfältig zu überprüfen und zu "approven" etc.

Alte Rechtschreibung hab' ich dann doch noch korrigiert, wo ich gleich dabei war :)
Details stehen auch im PR.
