### ISSUE TITLE
Metadaten der Kids-Folgen hinzufügen

### ISSUE THREAD

**Issue by YourMJK** [YourMJK/dreimetadaten#25]

**Comment by FPST-08** [comment]
[Metadaten.json](https://github.com/user-attachments/files/16390194/Metadaten.json)

Ich have versucht so gut es geht die Metadaten der Kids-Folgen zusammenzusuchen. Alle Serien-Folgen sind dabei, um die anderen Folgen kümmere ich mich auch noch demnächst. 

Ein paar Sachen dazu:

- Ab Folge 92 gibt es keine MusicBrainz ID. Folge 94 hat zwar einen Eintrag, aber keine ID, dort habe ich den Link hinterlegt.
- Folge 75 "Der Fußballroboter" gibt es aktuell nicht auf der offiziellen Seite zu finden. Deshalb fehlt dort Sprecher, Beschreibung und Link.
- Einige Folgen haben auf der offiziellen Seite keine Sprecher angegeben. Diese werde ich noch versuchen zu ergänzen. 
- Ich weiß nicht, wie zwischen Beschreibung und Kurzbeschreibung differenziert wird. Unter "Inhalt" auf der offiziellen Seite steht ein Text. Den habe ich unter Beschreibung vermerkt, aber bei der Original-Serie ist die Kurzbeschreibung wohl der Anfang der Beschreibung. Mit der Brechstange hätte ich das trennen können, aber bei einigen Beschreibungen hätte das  inhaltlich absolut keinen Sinn ergeben.
- Folge 57 hat 2 Autoren vermerkt, der eine hat die ursprüngliche Geschichte geschrieben, der andere überarbeitete und veröffentlichte. Ich bin mir unsicher, welchen Autor du vermerken möchtest.
- Hörspielskriptautor habe ich bisher nicht vermerkt.
- Die Autoren habe ich von Wikipedia, also womöglich mit Fehlern

**Comment by YourMJK** [comment]
Vielen herzlichen Dank!
Ich schau mir das ab Montag an.

**Comment by YourMJK** [comment]
> * Ich weiß nicht, wie zwischen Beschreibung und Kurzbeschreibung differenziert wird.

Seit Folge 217 ist die Beschreibung auf der Rückseite der CDs in zwei Absätze geteilt, erst ein fettgedruckter (= "kurzbeschreibung") und dann der Rest (= "beschreibung").
Siehe hier: [Discogs](https://i.discogs.com/3ZPy63b5Mx7S3P-STlr9KCvhL7DkVOe5K-wbfrBPM_0/rs:fit/g:sm/q:90/h:467/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIzOTcw/MDA1LTE3MDQyNTA3/NDUtNTE0Ni5qcGVn.jpeg)

Bei den Kids-Folge scheinen sie seit Folge 92 etwas ähnliches zu machen, da gibt es auch immer zuerst einen fettgedruckten Part: [Discogs](https://i.discogs.com/hLDlomCJ7kIv4Nf58LCqsoOutQoRksyg7LsvnR4WCkU/rs:fit/g:sm/q:90/h:467/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMwMzM3/NTk1LTE3MTMwNDEw/NTgtNjIxNy5qcGVn.jpeg)

Wäre natürlich super, wenn du das noch übernehmen könntest! Bilder findet man z.B. auf Discogs.

> * Folge 57 hat 2 Autoren vermerkt, der eine hat die ursprüngliche Geschichte geschrieben, der andere überarbeitete und veröffentlichte. Ich bin mir unsicher, welchen Autor du vermerken möchtest.

Mit der neuen relationalen SQL-Datenbank kann ich problemlos mehrere Autoren (geordnet) eintragen – also gerne beide!
Im JSON werden die dann mit Komma getrennt zusammengefügt.

---

Vielen Dank nochmal!
In v2.0 werde ich das noch nicht übernehmen (will das erstmal fertig haben … feature-creep und so), aber gleich anschließend.

Ich überlege, einen Branch dafür anzulegen mit deinen Daten in die Datenbank eingepflegt und worauf du Schreibzugriff hast, falls du auch noch was ergänzen/korrigieren willst.

**Comment by FPST-08** [comment]
> Bei den Kids-Folge scheinen sie seit Folge 92 etwas ähnliches zu machen

Dann werde ich mich für die Folgen das noch differenzieren.
> In v2.0 werde ich das noch nicht übernehmen

Dann habe ich keinen Stress beim Nachtragen :)
> Ich überlege, einen Branch dafür anzulegen mit deinen Daten in die Datenbank eingepflegt und worauf du Schreibzugriff hast

Das wäre super. Wie gesagt besonders die Apple Music IDs fehlen noch, dann könnte ich unter Anderem diese relativ einfach ergänzen.

**Comment by YourMJK** [comment]
> Dann werde ich mich für die Folgen das noch differenzieren.

Super, danke!

Ein Problem bei deinem JSON ist mir noch aufgefallen:
Die Reihenfolge im `"sprechrollen"`-Array entspricht nicht der Reihenfolge auf der offiziellen Seite.
Insbesondere werden Erzähler, Justus, Peter und Bob nicht immer zuerst genannt.

Das wäre schon recht wichtig, vielleicht kannst du deinen Code noch entsprechend anpassen? :)

**Comment by YourMJK** [comment]
Habe jetzt [einen neuen Branch](https://github.com/YourMJK/dreimetadaten/tree/kids) erstellt, in welchem das Schema schon vorbereitet wäre für die Kids-Folgen.

Wenn du die Daten soweit hast, kannst du entweder einen PR erstellen oder einfach so schicken, dann pflege ich sie in die Datenbank ein.

**Comment by FPST-08** [comment]
@YourMJK 
Geht es nur darum, dass Erzähler und die drei als erste genannt werden? Auf der offiziellen Seite sind die Sprecher nicht erkennbar geordnet (siehe z. B. [hier](https://www.dreifragezeichen-kids.de/produktwelt/produkt-details/fluch-des-goldes-1) Ich kann Erzähler und die drei nach vorne ziehen, aber den Rest sortieren macht eigentlich keinen Sinn. Ich habe jetzt Erzähler und die drei vorgezogen und der Rest ist alphabetisch sortiert. 

> Bei den Kids-Folge scheinen sie seit Folge 92 etwas ähnliches zu machen

Das habe ich soweit jetzt auch umgesetzt. Bei Folge 93 ist die Kurzbeschreibung allerdings fast gleichlang wie die Beschreibung. Ich habe das fett gedruckte trotzdem extrahiert. 

Die Apple Music Ids habe ich auch hinzugefügt. 

Direkt zum Branch kann ich nicht hinzufügen, weil ich mich nicht mit SQL auskenne. 

[Kids-Serie.json](https://github.com/user-attachments/files/16817353/Kids-Serie.json)

**Comment by YourMJK** [comment]
> Geht es nur darum, dass Erzähler und die drei als erste genannt werden? Auf der offiziellen Seite sind die Sprecher nicht erkennbar geordnet

Ahh, ich hab' jetzt erst gesehen, dass die auf der offiziellen Seite auch nicht sortiert sind.

Naja, idealerweise sollten sie die gleiche Reihenfolge haben, wie auf dem CD-Inlay.  
Siehe [hier](https://i.discogs.com/PBcdWTGYvR_IHCmLVqAlAF5nh8yUEm7JkraKrVNTiYI/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTc3NDY3/MjYtMTQ0ODA2MDQ0/MC0yMzg3LmpwZWc.jpeg) für deine Beispielfolge.

Habe bei Discogs jetzt stichprobenartig *keine* Folge gefunden, bei der ein Bild der Sprecherliste *nicht* vorhanden war, das könnte man eventuell als Quelle noch nutzen, um die richtige Sortierung zu bekommen.  
Das ist aber wahrscheinlich eher was für die Zukunft, das wäre viel manuelle Arbeit … oder vielleicht kann man das an eine multi-modale KI delegieren …?

> Ich habe jetzt Erzähler und die drei vorgezogen und der Rest ist alphabetisch sortiert.

Ich denke, das reicht erstmal, danke :)

> Das habe ich soweit jetzt auch umgesetzt.
> Die Apple Music Ids habe ich auch hinzugefügt.

Danke!

> Direkt zum Branch kann ich nicht hinzufügen, weil ich mich nicht mit SQL auskenne.

Kein Problem, das mach' ich gern.
Bin erstmal die nächsten 10 Tage noch im Urlaub, kümmere mich danach darum.

**Comment by YourMJK** [comment]
@FPST-08

> [Kids-Serie.json](https://github.com/user-attachments/files/16817353/Kids-Serie.json)

Deine hochgeladene JSON scheint fehlerhaft zu sein.  
Darin gibt es weder die erwähnten Kurzbeschreibungen, noch die Apple Music IDs.

Hast du die Felder evtl. beim Export vergessen?

**Comment by FPST-08** [comment]
@YourMJK 

Oh sorry. Ich hatte nur die alten Felder exportiert. Hier ist die Datei mit AMIDs und Kurzbeschreibungen.

[Kids-Serie.json](https://github.com/user-attachments/files/16989047/Kids-Serie.json)

**Comment by YourMJK** [comment]
Die Sprecher von Folge 76 und 85 sind noch fehlerhaft (da stehen jeweils sowohl in "rolle" und "sprecher" beides als ein String) und am Ende der Apple Music IDs hat sich ein "\r" eingeschlichen, aber das korrigiere ich selbst noch.

**Comment by YourMJK** [comment]
Das Problem mit den doppelten Sprechrollen betrifft mindestens Folge 16–18 und dort sind auch manchmal welche aufgelistet, die auf der offiziellen Seite zu der Folge gar nicht auftauchen.

Ich denke hier gab es irgendeinen Bug, sodass Sprecher (von Folge 16?) in die nächsten Folgen kopiert wurden.  
Vielleicht versuche ich das die Tage selbst noch einmal zu überprüfen.

FYI, hier wär meine korrigierte JSON soweit:  
[Kids-Serie_fixed.json](https://github.com/user-attachments/files/17037033/Kids-Serie_fixed.json)

Ein paar Namen, Tippfehler, Formatierungen und sonstige Kleinigkeiten habe ich auch ausgebessert.

**Comment by FPST-08** [comment]
> Die Sprecher von Folge 39, 43, 48, 50, 55, 58, 75, 81 sind leer
Für diese Folgen sind keine Sprecher auf der offiziellen Seite gelistet
> von 76, 77, 85 sind sie noch fehlerhaft
Weil bei diesen Folgen auf der Seite die Sprecher nicht durch ein "-" sondern einen ":" getrennt sind. Ist mir gerade erst aufgefallen, aber das hast du ja schon korrigiert.

> dort sind auch manchmal welche aufgelistet, die auf der offiziellen Seite zu der Folge gar nicht auftauchen.
Hast du das schon korrigiert oder soll ich mich darum kümmern?

> Ich denke hier gab es irgendeinen Bug, sodass Sprecher (von Folge 16?) in die nächsten Folgen kopiert wurden.
Irgendwas in die Richtung hab ich nicht gefunden, aber vielleicht habe ich auch einfach da manuell Fehler gemacht

**Comment by YourMJK** [comment]
> Hast du das schon korrigiert oder soll ich mich darum kümmern?

Hab ich/mach ich :)

**Comment by YourMJK** [comment]
> Auf der offiziellen Seite sind die Sprecher nicht erkennbar geordnet
> Ich habe jetzt Erzähler und die drei vorgezogen und der Rest ist alphabetisch sortiert.

Ich hab' mir das selber nochmal angeschaut und festgestellt, das die Sprecher auf den offiziellen Seiten tatsächlich *doch* sortiert sind (wie auf dem CD-Inlay), bis auf die Folgen 3–15 und 49.

Also fand mir das mit dem alphabetischem doch suboptimal, weswegen ich für die korrekte Reihenfolge das HTML nochmal geparset und mich beim Rest an den Discogs-Bilder orientiert habe.

Was mir außerdem aufgefallen ist an den offiziellen Daten:  
* 57 stimmt nicht mit CD überein und tauscht ab der Hälfte die Reihenfolge von "Rolle - Sprecher" zu "Sprecher - Rolle"

**Comment by YourMJK** [comment]
Eine Kleinigkeit ist bei deinem Parsing noch schief gelaufen: Doppelnamen, die einen Bindestrich enthalten wurden abgeschnitten.

Hab' das alles und noch ein paar Kleinigkeiten korrigiert. Werde die Daten jetzt so übernehmen :)

[Kids-Serie_fixed2.json](https://github.com/user-attachments/files/17164279/Kids-Serie_fixed2.json)

**Comment by YourMJK** [comment]
Für die noch fehlenden Kapiteldaten von 92–97 habe ich #66 eröffnet.
