### ISSUE TITLE
Verlinkung externer Projekte im README

### ISSUE THREAD

**Issue by MeFisto94** [YourMJK/dreimetadaten#29]
Hey, nicht direkt ein Bug/Feature, aber ich wollte euch nicht vorenthalten, dass ich (primär für meinen privaten Gebrauch und um Svelte/Tailwind zu lernen) einen Simplen Folgenvorschlager gebaut habe: https://github.com/MeFisto94/ddf-random

![img](https://github.com/MeFisto94/ddf-random/blob/1042c3a2f553bb32d3e8d99dd329a79573c1b7c9/example.png?raw=true)

Wenn v2 da ist, könnte man das schön mit einem Backend Teil versehen und zahlreiche Filter zu Sprechern oder anderen Begebenheiten erweitern. Aktuell ist es frontend-only, aber die Serien,json muss aufgrund von CORS im Repo gepflegt sein.

**Comment by YourMJK** [comment]
Cool, es freut mich immer, wenn andere diesen Datensatz in ihren Projekten verwenden! :)

Bzgl. des Backend-Teils, redest du da von deinem oder meinem Projekt?
Aktuell betreibe ich die Website noch komplett statisch und habe erstmal nicht vor, das zu ändern.

**Comment by YourMJK** [comment]
Mit v2.0 wird hier auf GitHub auch ein ordentliches README hinzugefügt.

Ich glaube, da wäre eine Sektion mit Verlinkungen zu Projekten (wie deines hier), die diesen Datensatz verwenden, eine ganz nette Idee :)

**Comment by YourMJK** [comment]
Ist jetzt ab [v2.0](https://github.com/YourMJK/dreimetadaten/tree/v2.0) im README verlinkt.
