### ISSUE TITLE
SSL/TLS für dreimetadaten.de

### ISSUE THREAD

**Issue by MeFisto94** [YourMJK/dreimetadaten#30]
Das sollte in Zeiten von Let's Encrypt kein Problem sein.
Umgekehrt, wenn man aber z.B. Alben-Cover in eine SSL Seite einbinden will, verbietet das der Browser neuerdings als Mixed-Content.

**Comment by YourMJK** [comment]
Das stimmt natürlich.  
Ich würde es optional anbieten, d.h. ohne Redirect, sodass normales HTTP auch noch funktioniert.

**Comment by YourMJK** [comment]
Ist jetzt beides verfügbar (ohne Redirect):
* **https://dreimetadaten.de**
* http://dreimetadaten.de
