### ISSUE TITLE
Falsche Länge Folge 168

### ISSUE THREAD

**Issue by ph4nt0m** [YourMJK/dreimetadaten#33]
Bei Folge 168 passen die Zeitangaben für Kapitel 4 und 10 aus der [metadata.json](http://dreimetadaten.de/data/Serie/168/metadata.json) nicht:

**4\. Merkwürdiger Fluchtweg** hat laut Metadaten 836730 ms, tatsächlich (laut XLD-Log) 838280 ms
**10\. Justus ist nicht nett** hat laut Metadaten 388590 ms, tatsächlich (laut XLD-Log) 387040 ms

Die zugehörige [ffmetadata.txt](http://dreimetadaten.de/data/Serie/168/ffmetadata.txt) enthält die gleichen abweichenden Werte. Könnten diese evtl. aus der ersten Pressung stammen, welche in Kapitel 5 bekanntermaßen einen Schnittfehler/Tonfehler hat? Das XLD-Log dürfte jedenfalls von der korrigierten Fassung stammen (die Werte kann ich bestätigen).

**Comment by YourMJK** [comment]
Vielen herzlichen Dank, ich schau mir das nochmal an!

Von dem Schnittfehler und darauffolgenden Neupressungen wusste ich nichts …
Weißt du, ob es da vielleicht noch andere Folgen gibt, bei denen man die Zeitangaben überprüfen sollte?

**Comment by ph4nt0m** [comment]
Über den Fehler in Folge 168 wird z.B. [hier](https://www.rocky-beach.com/hoerspiel/fehler/fehler151-175.html) und [hier](https://www.hoernews.de/fragezeichen/168.html) berichtet. 

Weitere mir bekannte fehlerhafte Erstauflagen gibt es bei den Folgen 138 (schlechte Tonqualität vor allem des Erzählers) und 144 (Speed-Down, die Stimmen scheinen dadurch deutlich zu tief). Hier entsprechen deine Zeitangaben in den Metadaten sowie die AccurateRip-IDs aus den XLD-Logs aber bereits den korrigierten Fassungen.

**Comment by YourMJK** [comment]
Ich habe mir das jetzt genauer angeschaut und tatsächlich sind die Kapitel schon so richtig, wie sie im JSON sind!

[Auf MusicBrainz](https://musicbrainz.org/release/bdb3fed3-c391-4a6c-9846-3b48118808ca) sind beide CDs aufgeführt, sogar schön mit Erklärung.
Die erste mit der fehlerhaften Tonwiederholung (VOozzPAS5i_OTXfHg3REA6kJea8-) und die zweite korrigierte (C0a7iNBLpwrDsEQAL88ztRcFXTU-).
Ich besitze die zweite und die Zeitangaben aus dem XLD-Log stimmen auch mit der aus MB überein (minus dem 2s Pre-Gap).

Allerdings stimmen auf der zweiten CD die Zeitangaben der Kapitel nicht mehr, die haben sie vergessen zu korrigieren!
Beim vierten Kapitel ("Merkwürdiger Fluchtweg") haben sie die fehlerhaften 1560ms (117 Sektoren) wieder rausgenommen, aber die Tracks gleich gelassen. Deswegen ist der Start aller darauffolgenden Kapitel nach hinten verschoben.

Ich habe das damals (März 2019) schon manuell korrigiert, indem ich die 1560ms nicht am Ende des letzten Kapitels, sondern eben am Ende von Kapitel 4 rausgenommen habe.

Sollte also alles so passen :)
Aber trotzdem danke für's Aufmerksam sein und Bescheidgeben!

**Comment by ph4nt0m** [comment]
> Allerdings stimmen auf der zweiten CD die Zeitangaben der Kapitel nicht mehr, die haben sie vergessen zu korrigieren! Beim vierten Kapitel ("Merkwürdiger Fluchtweg") haben sie die fehlerhaften 1560ms (117 Sektoren) wieder rausgenommen, aber die Tracks gleich gelassen. Deswegen ist der Start aller darauffolgenden Kapitel nach hinten verschoben.

Du meinst, der Verlag hat das vergessen? Musicbrainz bildet die Kapitel ja nur ab, wie sie technisch auf der CD vorhanden sind. Dass in der korrigierten zweiten Pressung die Kapitelgrenzen verschoben sind, kann ich bestätigen, allerdings erst ab dem Übergang von Kapitel 5 zu Kapitel 6. Ich habe eine Kopie der ersten Ausgabe hier und Kapitel 4 ist in beiden identisch. Da die Wiederholung in Kapitel 5 auftritt und dann herausgeschnitten wurde, ist es eigentlich plausibel, dass nur die nachfolgenden Kapitelübergänge in Mitleidenschaft gezogen wurden. Wenn man das logisch korrigieren wollte, müsste man die 1560 ms somit am Ende von Kapitel **5** herauskürzen, nicht Kapitel 4.

Wie dem auch sei, ich hatte angenommen, dass die Metadaten genau den technischen Zustand der Original-CDs widerspiegeln und keine manuellen Korrekturen umfassen, aber wenn genau das die Idee dahinter ist, kann man es ja nachvollziehen. Es ist schließlich dein Projekt. :)

**Comment by YourMJK** [comment]
> Du meinst, der Verlag hat das vergessen? Musicbrainz bildet die Kapitel ja nur ab, wie sie technisch auf der CD vorhanden sind.

Ja genau, Sony/Europa, wer auch immer die CD gemastert hat. Logisch :)

> Wenn man das logisch korrigieren wollte, müsste man die 1560 ms somit am Ende von Kapitel 5 herauskürzen, nicht Kapitel 4.

Oha, da hast du Recht …
Ich hab mir das gerade nochmal angehört und eigentlich klingt es so, wie ich es jetzt hatte, ziemlich richtig. Genau zum Start vom Kapitel 5 ist der Szenenwechsel: Die Musik ist ausgefadet und Blackey fängt an zu krächzen.
Wenn ich den Start von Kapitel 5 stattdessen wieder nach hinten verschiebe, wie im Original, dann ist Blackey abgeschnitten, allerdings fängt aber Justus genau an der Stelle zu reden an.

Schwer zu sagen, was also hier richtig sein soll.
Was auch immer der Grund für die Duplikation in 5. war, ich könnte mir schon vorstellen, dass dadurch auch der _Start_ von 5. ungewollt mitverschoben wurde.

Bei den darauffolgenden Kapiteln ist es ganz offensichtlich zu hören, da ist jedes Mal der Sprecher mitten im Satz abgeschnitten. Und mit der Korrektur passt es wieder.

Schade, dass es keine digitalen Angebote mit Kapiteln gibt, wo man das nochmal nachhören könnte.  
Die Streaming-Versionen haben ja nur willkürliche Tracks alle ~2min …
Vielleicht finde ich noch was.

> ich hatte angenommen, dass die Metadaten genau den technischen Zustand der Original-CDs widerspiegeln und keine manuellen Korrekturen umfassen

Das versuche ich natürlich größtenteils, aber m.M.n. sind **korrekte** Daten > **originalgetreue** Daten.  
In den Beschreibungen und Sprecherdaten habe ich ja auch einiges an Tippfehlern korrigieren "müssen".

Ich versuche es immer möglichst objektiv zu halten und nichts Subjektives einfließen zu lassen!

**Comment by ph4nt0m** [comment]
Gibt es denn noch weitere Folgen, bei denen du eine solche händische Korrektur der Kapitelgrenzen vorgenommen hast? Ich stelle mir gerade die Frage, ob man das irgendwo notieren könnte, weil es ja durchaus eine interessante Information ist, aber mir fällt spontan keine gute Möglichkeit ein.

Es wäre natürlich auch gut zu wissen, auf welche CD-Pressung sich die Angaben jeweils beziehen (wie man an den Folgen 138, 144 und 168 sieht, haben diese ja unterschiedliche Spieldauern), aber das sprengt dann wohl den Rahmen. Leider finde ich im Netz keine Gesamtübersicht zu solchen korrigierten Fassungen, aber vermutlich gibt es noch mehr davon.

Da das eigentliche Thema geklärt ist, schließe ich dieses Issue nun. Und bei dieser Gelegenheit möchte ich auch meinen Dank für deine großartige Arbeit und die sehr hilfreiche Datenbasis aussprechen!

**Comment by YourMJK** [comment]
> Gibt es denn noch weitere Folgen, bei denen du eine solche händische Korrektur der Kapitelgrenzen vorgenommen hast?

Nein, ich glaube nicht. Kann ich gerne nochmal mit dem Logs nachchecken lassen.

Das einzige wäre die Spezial-Folge "House of Horrors".
Das ist ja dieser Mitratefall, der sich über zwei CDs verteilt. Und damit die Tracknummern, zu denen man navigieren muss, Sinn ergeben, haben sie auf CD2 am Anfang so viele Dummy-Tracks eingefügt, wie CD1 Tracks hat.
Die habe ich in den (zusätzlichen) gemergten Kapiteln ausgelassen, damit in der digitalen Version die Tracknummern wieder die richtigen sind.

Aber mit diesen implizierten Änderungen bin ich auch nicht zufrieden, deswegen hab ich ja jetzt [eine vernünftige SQL-Datenbank erstellt](https://github.com/YourMJK/dreimetadaten/pull/32), wo die CDs, Tracks, Teile und Kapitel extra modelliert sind (und nicht wie im JSON-Modell vermischt ist).
Jetzt verweist jedes Kapitel auf einen Track auf einer CD, somit ist das Weglassen und Verschmelzen von Tracks mehrerer CDs explizit hinterlegt.

Das JSON-Modell leite ich dann in Zukunft davon ab, aber lass es vielleicht so vereinfacht, wie es jetzt ist (damit es für andere auch einfacher zu parsen ist).

> Ich stelle mir gerade die Frage, ob man das irgendwo notieren könnte

Das dachte ich mir gestern auch … vielleicht fällt mir was ein.

> Es wäre natürlich auch gut zu wissen, auf welche CD-Pressung sich die Angaben jeweils beziehen

Ebenso, das ist mir auch in den Sinn gekommen. Ich habe nämlich entdeckt, dass ich zu jeder CD von XLD noch ein Cue-Sheet habe, in dem die Katalog-Nummer und die FreeDB-DiscID gespeichert ist. Beides ist auch in MusicBrainz zu finden.
Ich werde das noch hinzufügen, damit wäre dann eindeutig die Folge und die CDs identifiziert.
