### ISSUE TITLE
Typo bei Beschreibung von Folge 96

### ISSUE THREAD

**Issue by FPST-08** [YourMJK/dreimetadaten#35]
"Jusuts" anstelle von Justus

**Comment by YourMJK** [comment]
Genau, das wurde in PR #24 mit allen anderen Beschreibungen korrigiert und ist noch im [v2.0](https://github.com/YourMJK/dreimetadaten/tree/v2.0)-Branch:
https://github.com/YourMJK/dreimetadaten/blob/v2.0/web/data/Serie/096/metadata.json#L6

v2.0 sollte dann bald fertig und live sein, kann sich nur noch um Tage/Wochen handeln …

Trotzdem vielen Dank für's Aufmerksam sein und Bescheid geben!
