### ISSUE TITLE
Metadaten der Multi-CD-Folgen

### ISSUE THREAD

**Issue by utack** [YourMJK/dreimetadaten#4]
Hi,  
  
eine Frage:
Spricht etwas dagegen die allgemeinen Metadaten der Jubliäumsfolgen auch nochmal in die jeweiligen "Teil-Metadaten" zu packen.
zB ist das autor oder veröffentlichsdatum der 100 ja auch für Teil 100A gültig.

Würde mich sehr freuen, ich will die Daten verarbeiten und es wäre deutlich mehr Aufwand wenn ich zwei json Dateien gleichzeitig verarbeiten müsste.

Danke!

**Comment by YourMJK** [comment]
Ich habe mich beim Entwerfen der Struktur der Metadaten dazu entschieden, dass die Teile einer Höreinheit keine redundanten Einträge aus dieser enthalten sollten, da sie die eh schon impliziert "erben".  
Das macht das Ganze weniger fehleranfällig und ergibt m.M.n. auch logisch/intuitiv mehr Sinn.

Nur wenn ein Metadatum nicht für alle Teile gleich ist, bekommt jeder Teil dazu einen Eintrag.

Die übergeordnete Höreinheit kann dann – wenn möglich – einen Eintrag haben, der die aus den Teilen zusammenführt. In diese Richtung kann es also schon eine gewisse Redundanz geben.
So mache ich das z.B. bei den Kapiteln (durch Aneinanderhängen) oder Sprechern (durch Vereinigung), siehe 100, 125, 150, 175.

Wenn du die Daten automatiert verarbeiten willst, würde ich dir empfehlen, entweder mit der kompletten JSON zu arbeiten, welche alle Folgen enthält (http://dreimetadaten.de/data/Serie.json), oder mit einer Datei pro Folge (http://dreimetadaten.de/data/Serie/100/metadata.json) – die Metadaten der Teile sind auch in dieser enthalten! Da musst du nicht zwei Dateien gleichzeitig parsen.

Generell sind die JSON-Dateien der Teile und Folgen ja nur Auszüge aus der eigentlichen Serie.json, quasi auf ihr "scope" begrenzt.

**Comment by YourMJK** [comment]
Die Logik, wie Teile die Metadaten der übergeordneten Folgen erben, kannst du dir hier abschauen (wie ich die `ffmetadata`-Dateien generiere):  
https://github.com/YourMJK/dreimetadaten/blob/cfd8f7d91ee9a8ae56f8419dcbedc398e7d9c2eb/D3F-MetadataExporter/D3F-MetadataExporter/FFmetadata.swift#L170-L194

Ist eigentlich ganz simple: wenn der Teil keinen eigenen Eintrag zu Sprecher, Autor, Hörspielskriptautor, Beschreibung oder Veröffentlichungsdatum hat, erbt er ihn.

Oder natürlich du nimmst gleich meine `ffmetadata`-Dateien her.

**Comment by utack** [comment]
Die Logik leuchtet ein
Vielen Dank!
