### ISSUE TITLE
Falsche Apple Music ID zu Folge 227

### ISSUE THREAD

**Issue by FPST-08** [YourMJK/dreimetadaten#48]
Der Link zum Album auf Apple Music ist https://music.apple.com/de/album/folge-228-der-ruf-der-krähen/1757389491?l=en-GB .
Somit ist die ID des Album 1757389491, allerdings verwendest du bei V2 beim Apple Music Link und bei https://v2.dreimetadaten.de/index/apple-music/ eine falsche/veraltete ID. 
Zudem sind die Daten bei V1 für Folge 227 vollständig, bei V2 jedoch noch nicht.

**Comment by YourMJK** [comment]
Danke, schau ich mir an!
Bin bisher noch nicht dazugekommen, die Änderungen für 227&228 in v2.0 zu mergen, kommt heute noch.

**Comment by YourMJK** [comment]
Du meintest Folge 228, oder?

Jetzt sollte alles wieder passen, Daten auf https://v2.dreimetadaten.de/ sind aktuell.

**Comment by FPST-08** [comment]
Ja sorry. Ich habe Folge 228 gemeint. Funktioniert jetzt alles wieder super.
