### ISSUE TITLE
Author von Folgen falsch

### ISSUE THREAD

**Issue by utack** [YourMJK/dreimetadaten#5]
Author von Folge 92 ist Ben Nevis, nicht Andre Minninger

**Comment by utack** [comment]
Generell ist das bei ein paar Folgen noch falsch
Ich gehe mal alle durch und schaue wo es noch ist. Zumindest bei der 94 auch

**Comment by YourMJK** [comment]
Du hast absolut Recht! Zumindest, wenn man den Daten auf der Wikipedia-Seite glauben darf.  

Ich hab das gerade mal schnell abgeglichen und für die Folgen **83, 84, 91–96, 98, 113 und 163** ist bei meinen Daten – wahrscheinlich fälschlicherweise – "André Minninger" als Autor angegeben.

Ich frag mich gerade, wie das passiert ist …  
Werde die auf alle Fälle manuell nochmal durchgehen und mit anderen Quellen abgleichen.  
Vielen Dank für den Hinweis!

**Comment by YourMJK** [comment]
[autoren_cfd8f7d.txt](https://github.com/YourMJK/dreimetadaten/files/10348059/autoren_cfd8f7d.txt)
[autoren_wiki.txt](https://github.com/YourMJK/dreimetadaten/files/10348060/autoren_wiki.txt)

**Comment by utack** [comment]
Vielen Dank für die fixe Korrektur!
