### ISSUE TITLE
Folge 230

### ISSUE THREAD

**Issue by JBlond** [YourMJK/dreimetadaten#57]
Zumindest der Titel und ein paar mehr Informationen habe ich schon dazu gefunden https://dervinylist.com/2023/03/16/die-drei-der-tag-der-toten/

**Comment by YourMJK** [comment]
Danke! Auf Amazon ist sie auch schon gelistet.

Ich werde überlegen, ob ich in Zukunft die Folgen schon früher hinzufügen kann.

**Comment by JBlond** [comment]
Das Datum wird der 06.09.2024
https://dreifragezeichen.de/produktwelt/vorschau
