### ISSUE TITLE
How to fetch all of the episodes at once

### ISSUE THREAD

**Issue by RobinWitt** [YourMJK/dreimetadaten#6]
Hallo YourMJK,
ich gehe mal davon aus das es in Ordnung ist wenn ich meine Anfrage auf deutsch formuliere...

Zurzeit mache ich ein Coding-Bootcamp und habe mich entschieden für mein Capstone eine 'Drei Fragezeichen' Begleit-App zu erstellen. Über googlen bin ich zu deiner metadaten Webseite gelangt, echt super!
Nun aber zu meiner Frage: Mir ist soweit klar wie ich eine einzelne Episode als json live fetchen kann.
z.B. "http://dreimetadaten.de/data/Serie/217/metadata.json"
Allerdings habe ich bisher nicht herausfinden können wie ich eine Liste der gesamten Folgen anfetche, beispielsweise für eine Overview Page.
Ist das überhaupt von dir so angedacht? Vielleicht kannst du mir einen Tipp geben.

Für den Anfang habe ich mir die Serie.json von der Webseite gedownloaded.

Schon mal vielen Dank im Voraus.
Liebe Grüße aus Leipzig
Robin

**Comment by RobinWitt** [comment]
Ich hab es soeben durch herumprobieren mit der URL herausgefunden! Case closed :)

**Comment by YourMJK** [comment]
Genau, unter http://dreimetadaten.de/data/Serie.json findest du immer die aktuelle gesamte Liste aller regulären Folgen.  
Im Repo sind das die Dateien *data/Serie.json* und *data/Master_Serie.json*, die sind alle identisch.

Ich denke http://dreimetadaten.de/data/metadata_structure.swift wirst du auch schon gefunden haben, das könnte recht hilfreich beim Parsen sein.

Solange die Requests nicht allzu viel werden, ist das absolut in Ordnung, die regelmäßig zu requesten.

Viel Erfolg mit deiner App!  
Über einen Shoutout würd ich mich freuen.

**Comment by RobinWitt** [comment]
Mit Parsen meinst du die Validierung der Daten nach Schema oder?

Die Requests sollten sich in Grenzen halten, da ich die App nur für dieses Projekt brauche und erstmal keinen 'echten' Use Case habe. Um sicher zu gehen werde ich so oft es geht einfach auf die lokale json fetchen.

Du wirst defintiv lobend erwähnt werden, wenn du einverstanden bist verlinke ich dein Gitub oder so?

Mein nächster Schritt, falls ich alles andere fertig habe, wäre im übrigen die Spotify API zu nutzen... na mal sehen.

Vielen Dank und schönes Wochenende dir!

**Comment by YourMJK** [comment]
> Mit Parsen meinst du die Validierung der Daten nach Schema oder?

Ja genau. 

> Die Requests sollten sich in Grenzen halten, da ich die App nur für dieses Projekt brauche und erstmal keinen 'echten' Use Case habe. Um sicher zu gehen werde ich so oft es geht einfach auf die lokale json fetchen.

Achso, dann ist es eh kein Problem.  
Da kann die App ruhig bei jedem Öffnen (und wenn der User es anfordert) aktualisieren, selbst wenn es bis zu 1000 User wären.

Wenn du es ein wenig intelligenter lösen willst, kannst du natürlich das zukünftige Veröffentlichungsdatum der nächsten Folge (welches ich immer reinschreibe) auslesen und für die Aktualisierung berücksichtigen.

> Du wirst defintiv lobend erwähnt werden, wenn du einverstanden bist verlinke ich dein Gitub oder so?

Klar, gern. Oder auch gern einfach die Website.

Viel Spaß, dir ebenfalls schönes Wochenende!
