### ISSUE TITLE
Migration von DdfGuide

### ISSUE THREAD

**Issue by selmaohneh** [YourMJK/dreimetadaten#62]
## Nochmal Moin!

Meine App, [der DdfGuide](https://github.com/selmaohneh/DdfGuide), ist schon vor 7 Jahren entsanden. Da haben wir uns leiden zeitlich knapp verpasst. 

Nun pflege ich aber aktuell genau die gleichen Daten wie du, und das ist natürlich Quatsch. Ich denke daher darüber nach zu dreimetadaten zu migrieren.

Für den DdfGuide werden die Daten plump in einer json-Datei auf Github gepflegt. Das ist quasi das Backend. :D Im jugendlichen Wahnsinn wurde sich dafür entschieden, weil die App komplett kostenlos laufen sollte. 

### IDs
Ich benötige zu jeder Folge eine eindeutige `guid`. Nutzer können sich Folgen favorisieren und/oder als gehört markieren. Dies muss über diese `guids` passieren, damit die Information bei einem Update, z.B. des Folgennamens, nicht verloren geht.
Du hast IDs in der SQL-DB. Diese müssten dann noch mit in das json gepackt werden. 

Dann hätte ich den Aufwand, meine bestehenden IDs auf deine IDs zu mappen. Alternativ könnten natürlich auch die IDs in der SQL-DB angepasst werden und dort[ *meine* IDs](https://github.com/selmaohneh/DdfGuide/blob/master/dtos.json) eingetragen werden. Das verschiebt die Arbeit weg von mir direkt zu dir :D

### Amazon
Ich biete in der App einen Link zu Amazon an. Nicht zu Amazon-Music, sondern zum Amazon-Shop. Das ist ein Affiliate-Link zu der CD der Folge. Hierfür benötige ich die Amazon-ID der Folge. Sind das Metadaten, die du mit aufnehmen würdest? Diese sind ebenfalls hier zu finden: https://github.com/selmaohneh/DdfGuide/blob/master/dtos.json

### Links vs. IDs
Eher eine Anmerkung um ein paar Daten zu sparen: Es reicht die jeweilige ID für Amazon, iTunes, Spotify, etc. zu speichern. Der eigentlichen Link kann dann anhand der ID erstellt werden. Mit einer Amazon-ID kann dann beispielsweise sowohl zu Amazon-Music als auch zum Amazon Shop weitergeleitet werden.

### Kids-Folgen fehlen
Ich biete ebenfalls alle Folgen den Drei Fragezeichen Kids an. Die sind ja aber, laut deiner Email, schon in Arbeit :-)

## Zusammengefasst
Was sind deine Gedanken dazu? Ja/Nein/Vielleicht? Ich kann natürlich nur migrieren, wenn all diese Punkte geklärt sind. Ansonsten bleiben wir redundant und pflegen zwei mal die gleichen Daten. :D

# Tasks
- [x] #67
- [x] #68
- [x] #25
- [x] #69
- [x] Fehlende Folgen ergänzen

**Comment by YourMJK** [comment]
> Für den DdfGuide werden die Daten plump in einer json-Datei auf Github gepflegt. Das ist quasi das Backend. :D Im jugendlichen Wahnsinn wurde sich dafür entschieden, weil die App komplett kostenlos laufen sollte.

So lief das hier auch noch bis vor ein paar Monaten, bevor ich auf SQL migriert habe :D
Habe dann doch eingesehen, dass das keinen Sinn hat ohne Relationen. Jetzt leite ich das JSON nur noch aus der Datenbank ab.

## IDs
> Du hast IDs in der SQL-DB. Diese müssten dann noch mit in das json gepackt werden.

Sehe ich auch so.  
Hatte das eigentlich eh bei der Migration schon vor, keine Ahnung, wieso ich das dann doch gelassen habe.

> Dann hätte ich den Aufwand, meine bestehenden IDs auf deine IDs zu mappen. Alternativ könnten natürlich auch die IDs in der SQL-DB angepasst werden und dort[ _meine_ IDs](https://github.com/selmaohneh/DdfGuide/blob/master/dtos.json) eingetragen werden.

Meine IDs will ich eigentlich nicht ändern, dafür müsste ich meine Datenbank zu sehr umbauen.
Und der ganze Code basiert auch stark auf den rein numerischen IDs.

Ich fürchte, da musst du in den sauren Apfel beißen ;)
Ich kann dir gern beim Mapping helfen. Über die Europa-Nr. sollte sich ja schon das gröbste automatisch lösen lassen.

## Amazon
> Hierfür benötige ich die Amazon-ID der Folge. Sind das Metadaten, die du mit aufnehmen würdest?

Gerne! Das stand eh schon auf dem TODO: #28  
Vielen Dank, ich schau mir das an.

## Links vs. IDs
> Eher eine Anmerkung um ein paar Daten zu sparen: Es reicht die jeweilige ID für Amazon, iTunes, Spotify, etc. zu speichern. Der eigentlichen Link kann dann anhand der ID erstellt werden.

Ich weiß, ich hab' das ursprünglich u.a. so gemacht, weil sich das schöner in mein voriges Schema eingereiht hat.
Aber das stört mich auch immer mehr, v.a. weil jetzt noch mehr IDs dazukommen/gekommen sind. Hatte eh vor, das zu ändern.

Aktuell mache ich ja genau das Gegenteil, wenn ich die `/index/*`-Weiterleitungen generiere: nämlich die IDs aus den URLs ziehen. Bisschen bescheuert.

Wahrscheinlich werd ich das im gleichen Zuge mit umstellen und, wie du meinst, nur die IDs speichern.

## Kids-Folgen fehlen
> [Drei Fragezeichen Kids] sind ja aber, laut deiner Email, schon in Arbeit :-)

Genau, sind fast fertig! Ist in #25 getrackt.

 ## Zusammengefasst

Sind gute Punkte und sollte nicht zu viel Arbeit sein :)
Ich setz mich gleich nach den Kids-Daten dran!

**Comment by YourMJK** [comment]
Hier wäre schonmal eine Map von deinen IDs zu meinen als TSV:
https://gist.github.com/YourMJK/8297380b76d7b639b21256460857c565

Allerdings fehlen mir (noch) 8 Hörspiele: 3 Spezial-Folgen und die 5 Kids-Adventskalender:

``` tsv
b9c70d45-d025-4b21-bf22-587cfb9f2a72	Die drei ???	Master of Chess - Live & Unplugged
da7920e4-6b74-420b-aa20-ff54e2983e85	Die drei ???	Rocky Beach Radio Show
f4310157-f724-465e-8a8f-773de351fb47	Die drei ???	Die Welt der drei ???
79e53724-82d5-431a-95be-5775643c8144	Die drei ??? Kids	Adventskalender
1afe43f2-62a1-4622-a0a3-8861fb6a9a42	Die drei ??? Kids	Adventskalender - Ein Rätsel in 24 Tagen
f6483fb1-0e3f-45cb-832e-aeeeaaa8b005	Die drei ??? Kids	Adventskalender - 24 Tage im Weihnachtszirkus
2ffa7ad6-41e1-4417-bd7c-f0c6beb3c981	Die drei ??? Kids	Adventskalender - 24 Tage im Weihnachtsland
0227a399-f37f-4d48-8f2e-4a274744fba0	Die drei ??? Kids	Adventskalender - 24 Tage Chaos im Zoo
```

**Comment by selmaohneh** [comment]
Boah, du haust ja richtig einen Schlag rein. Ich hoffe ich komme dann zeitnah überhaupt dazu, das zu migrieren. :-O

**Comment by YourMJK** [comment]
Ach, die Map hatte ich mit `jq` und ein bisschen SQL ganz schnell über die Europa-Nummern bzw. Titel zusammen :D

Dank dessen ist mir auch ein Tippfehler in meinem Titel von Kids-Folge 47 aufgefallen.

**Comment by YourMJK** [comment]
Die IDs wären soweit fertig.

Bleiben noch die fehlenden Folgen, wobei ich die 5 Kids-Adventskalender bald hinzufügen werde.  
Die Frage ist: Kannst du so schon migrieren, oder brauchst du dafür die anderen drei Spezial-Folgen auch noch?

**Comment by selmaohneh** [comment]
wenn folgen bei der migration fehlen, verlieren meine benutzer die folge als "favorit" und ihr "gehört"-häckchen. das wäre bei 3 folgen nicht dramatisch, aber natürlich unangenehm. :-/ 
mein plan ist in einem release den switch komplett zu machen. beim start der app würde ich dann mit einer vollständigen tsv-datei einmal alles mappen.
ich würde deshalb wohl noch warten, bis du das go gibst, dass alle folgen da sind.

**Comment by selmaohneh** [comment]
und gibt es die möglichkeit ein komplettes json zu erstellen, in dem alle folgen enthalten sind?

ich müsse aktuell serie.json, spezial.json, …, kids.json herunterladen und die dann zusammendröseln. 

das würde die ganze geschichte für mich deutlich robuster machen.

**Comment by YourMJK** [comment]
> ich würde deshalb wohl noch warten, bis du das go gibst, dass alle folgen da sind.

Versteh ich. Dann werde ich die anderen demnächst wahrscheinlich noch hinzufügen.  
Auch wenn "Die Welt der drei Fragezeichen" eigentlich kein richtiges Hörspiel mit Handlung und Sprechern ist und deswegen mMn. nicht zu den anderen in die "Spezial"-Kategorie passt.  
Vielleicht kommt das in eine neue Kategorie "Andere" …

> und gibt es die möglichkeit ein komplettes json zu erstellen, in dem alle folgen enthalten sind?

Klar, das hatte ich eh vor mit #72!  
Ist lang überfällig.

**Comment by YourMJK** [comment]
@selmaohneh

> und gibt es die möglichkeit ein komplettes json zu erstellen, in dem alle folgen enthalten sind?

Gibt es jetzt :)  
https://dreimetadaten.de/data/Alle.json

**Comment by selmaohneh** [comment]
Lohnt es sich noch eine interpreter-property einzuführen? Oder eine Art type?

Ich habe mit dem neuen Alle.json (vielen Dank!) keine Möglichkeit, mir das wieder in Drei ??? und Kids aufzudröseln, oder?

interpreter + Nummer stellt dann eine reguläre Folge dar. interpreter + keine Nummer eine Sonderfolge. Damit könnte man arbeiten.

Oder mit types: dreifragezeichen, dreifragezeichen-special, dreifragezeichenkids, dreifragezeichenkids-special, …

**Comment by YourMJK** [comment]
> Ich habe mit dem neuen Alle.json (vielen Dank!) keine Möglichkeit, mir das wieder in Drei ??? und Kids aufzudröseln, oder?

Doch klar, eigentlich schon!

Das hat die folgende Form, wie die anderen Gesamt-JSONs (Serie.json etc.) auch:

``` json
{
  "serie" : [
    ...
  ],
  "spezial" : [
    ...
  ],
  "kurzgeschichten" : [
    ...
  ],
  "die_dr3i" : [
    ...
  ],
  "kids" : [
    ...
  ]
}

Das heißt beim Parsen bzw. wenn du das Objekt ausliest, weißt du ja über den Pfad, welcher Sammlung sie angehören.

Das sollte reichen, oder?

**Comment by YourMJK** [comment]
Jetzt fehlen übrigens nur noch drei:

``` tsv
b9c70d45-d025-4b21-bf22-587cfb9f2a72	Die drei ???	Master of Chess - Live & Unplugged
da7920e4-6b74-420b-aa20-ff54e2983e85	Die drei ???	Rocky Beach Radio Show
f4310157-f724-465e-8a8f-773de351fb47	Die drei ???	Die Welt der drei ???
```

Habe das TSV geupdatet:  
https://gist.github.com/YourMJK/8297380b76d7b639b21256460857c565

**Comment by YourMJK** [comment]
@selmaohneh
Jetzt sind alle fehlenden Folge ergänzt und die [TSV-Map](https://gist.github.com/YourMJK/8297380b76d7b639b21256460857c565) ist vollständig!

Ich glaube von meiner Seite sollte dann alles passen und der Migration nichts mehr im Wege stehen, oder?

**Comment by selmaohneh** [comment]
Yep, denke schon. Ich melde mich, falls nicht. Bin vorher jedoch noch an einem anderen Projekt dran. Danke schonmal im voraus für die Arbeit. :-)
