### ISSUE TITLE
Amazon-IDs in Datenbank aufnehmen

### ISSUE THREAD

**Issue by YourMJK** [YourMJK/dreimetadaten#68]
Daten aus [DdfGuide/dtos.json](https://github.com/selmaohneh/DdfGuide/blob/master/dtos.json)

- [x] Amazon Music
- [x] Amazon Shop (CD)

**Comment by YourMJK** [comment]
@selmaohneh Ein paar der `AmazonAlbumId`s gibt es nicht (mehr), z.B. `B01CURZRWG` für *… und der Super-Papagei*.  
Gibt es eine einfache Möglichkeit, die nicht mehr verfügbaren IDs zu aktualisieren? Wie hast du die anfangs gesammelt?

**Comment by selmaohneh** [comment]
Ich hab die ganz stumpf von Amazon geholt. Album bei Amazon suchen und ID aus der URL friemeln. :-/

**Comment by YourMJK** [comment]
@selmaohneh  
Sollen die IDs für den Amazon-Shop (d.h. für die CD) sein, oder für Amazon Music?  
Das sind nämlich nicht die gleichen, zumindest soweit ich rausgefunden habe.

Nicht die URL bestimmt, ob du zu *Shop* oder *Music* kommst, sondern die ID.  
Z.B. für *… und der Super-Papagei*:
* *Shop*: https://www.amazon.de/gp/product/B00005QXM1
* *Music*: https://www.amazon.de/gp/product/B01CURZRWG

---

Ich habe außerdem eine doppelte `AmazonAlbumId` entdeckt (ist die einzige):  
Sowohl Folge 218 als auch 219 haben `B0B63CDTXC`. Denke mal ein Copy-Paste-Fehler.

Aber auch hier kann ich die keine Produktseite mit dieser ID erreichen:  
https://www.amazon.de/gp/product/B0B63CDTXC

**Comment by selmaohneh** [comment]
Die ID soll zum Shop führen. Ich habe einen "Einkaufswagen-Button" in der Übersicht zu jeder Folge.

Joa, dass sich über die Jahre ein paar Fehler eingeschlichen haben, glaube ich gerne. :-D

**Comment by YourMJK** [comment]
@selmaohneh  
Okay … ich frag nur, weil ich jetzt mal die URLs durchprobiert hab und die meisten tatsächlich zu *Amazon **Music*** führen.

* Folge 1–215 ist alles ***Music*** (bis auf 191, 192, 193, 195 und 213, die sind nicht mehr gültig)
* Folge 216–230 ist alles ***Shop*** für die CD/Vinyl (bis auf 218, 219 und 220, die sind auch nicht gültig)
* Spezial-Folgen und Kurzgeschichten ist alles ***Music***
* Kids-Folgen ist auch alles ***Music***

Wie wollen wir das machen?  
Reichen dir die IDs für Amazon Music oder brauchst du die für die CDs im Shop auch noch?

**Comment by selmaohneh** [comment]
Shop brauche ich definitiv. :-/ Krass, dass die alle nicht gehen. Gibt es da ein wildes Amazon forwarding wenn man nicht Amazon music hat oder so vllt?

**Comment by selmaohneh** [comment]
Tatsache, geht bei mir jetzt auch zu Amazon music. Das muss ich definitiv wieder ändern.

**Comment by YourMJK** [comment]
Also ich komm' eigentlich immer bei Amazon Music raus, auch wenn ich nicht angemeldet bin.

Wäre cool, wenn du die Shop-IDs für mich sammeln könntest, dann würde ich einfach beides in meine Datenbank einbauen :)
In der Zwischenzeit sammle ich schonmal die restlichen fehlenden Music-IDs.

**Comment by YourMJK** [comment]
Shop-IDs für 1–230 hab' ich schonmal.
Die Verlinkungen auf der offiziellen Seite (für welche ich die Links ja schon habe) waren ganz hilfreich.
