### ISSUE TITLE
Apple Music-IDs von Kids-Folgen 93–96 verschoben

### ISSUE THREAD

**Issue by FPST-08** [YourMJK/dreimetadaten#83]
Ich wollte eigentlich sagen, dass Folge 93: Die Geistermühle doppelt auf Apple Music verfügbar ist, aber nur einmal mithilfe der Apple Music ID die Daten direkt aufgerufen werden können. Dabei habe ich allerdings etwas anderes entdeckt:
Anstelle dass die andere ID 404 ausgibt, erhalte ich die Metadaten zu der darauffolgenden Folge 94. 
Die ID von Folge 96 gibt die Daten von 93 aus.
Die ID von Folge 95 gibt die Daten von 96 aus.
Die ID von Folge 94 gibt die Daten von 95 aus.
Die IDs von Folge 93 geben die Daten von 93 und 94 aus.

Wäre super, wenn du das beheben könntest. Danke

**Comment by YourMJK** [comment]
Oh je, entweder war ich da letztens unaufmerksam beim Einfügen der IDs oder Apple/Europa hat die nochmal jongliert …  

Aber merkwürdig, dass 93 zweimal existiert.  
Wie ich gerade entdeckt hab' nämlich einmal als [Compilation](https://music.apple.com/de/artist/die-drei-kids/305761269/see-all?section=compilation-albums) und einmal als [Album](https://music.apple.com/de/artist/die-drei-kids/305761269/see-all?section=full-albums).  
Die Folgen 97, 95, 94, 92–85, 83, 82 gibt es nur als Compilations.

Auf jeden Fall vielen Dank für's Bescheid geben! Gut, dass es dir aufgefallen ist.  
Werde ich gleich korrigieren.

**Comment by YourMJK** [comment]
Habe mich bei der 93 jetzt für die Album-Version entschieden.

**Comment by YourMJK** [comment]
Ups, hatte die URLs für die iTunes-Coverbilder vergessen … die wurden natürlich auch aus den falschen IDs generiert.
